kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-users
spec:
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
