kind: PersistentVolume
apiVersion: v1
metadata:
  name: library-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/library-pv
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: library-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: library-pv