apiVersion: v1
kind: Secret
metadata:
  name: library-secret
type: Opaque
data:
  secret_key: ZGphbmdvLWluc2VjdXJlLTgkI3QqYzg3JSRzYWxfIV51K155Yjd6JHp3cHd2dXZibWw4K2M2aXRuMnY1YnV4M3Bh
  database_username: cm9vdA==
  database_password: dG9vcg==