# Generated by Django 4.0.4 on 2022-04-29 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_rename_genre_id_books_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
