apiVersion: v1
kind: Secret
metadata:
  name: user-secret
type: Opaque
data:
  secret_key: ZGphbmdvLWluc2VjdXJlLTc1Nmx0KihnQEAyZndAQGgmJGhqPTRvPXp2ZCVzaSk2X2IjYzRrai12ejV0dzdeI3Rf
  database_username: cm9vdA==
  database_password: dG9vcg==