kind: PersistentVolume
apiVersion: v1
metadata:
  name: shop-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/shop-pv
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shop-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: shop-pv