apiVersion: v1
kind: Secret
metadata:
  name: shop-secret
type: Opaque
data:
  secret_key: ZGphbmdvLWluc2VjdXJlLSppMSUrKzUyMCQqbXdzZjhsJnopXm15KSUyK3kkMXlqMWwmKWUkNSYjbF4rKSRrYzEx
  database_username: cm9vdA==
  database_password: dG9vcg==